---
title: "Optimal coordination - general experiment analysis."
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(magrittr)
library(readr)
library(gridExtra)
library(readr)
library(scales)
library(dplyr)
library(NNTbiomarker)

normalize <- function(x) {
    return ((x - min(x)) / (max(x) - min(x)))
}
find_point <- function(x, y, point){
  i <- argmin(x, target = point)
  return(c(x[i], y[i]))
}
ms <- 1e3
```


# Load and process

```{r, message=FALSE}
# Sparse
freqs <- c("8")#, "40", "60")
results <- NULL

exp <- "127a_1"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)

exp <- "127a_5"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)

exp <- "127a_9"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)


exp <- "127b"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)

# - 
results %>% 
  filter(n_spikes_ref > 0) %>% 
  # Add delta_spikes
  mutate(delta_spikes = n_spikes - n_spikes_ref) %>% 
  # Re-norm V_osc
  mutate(V_osc = V_osc - V_osc_ref) -> results

# -
rm(tmp, df)
```

```{r}
results %>% 
  ggplot(aes(x=As, y=variances_pop*ms, color=exp, shape=exp)) +
  geom_line(size=2, alpha=0.2) +
  geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

```{r}
results %>% 
  ggplot(aes(x=As, y=n_spikes_pop, color=exp, shape=exp)) +
  geom_line(size=2, alpha=0.2) +
  geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

```{r}
results %>% 
  ggplot(aes(x=As, y=errors_pop*ms, color=exp, shape=exp)) +
  geom_line(size=2, alpha=0.2) +
  geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

```{r}
tmp <- results
tmp$state <- rep("pathological", nrow(tmp))
m <- tmp$V_osc/tmp$V_comp < 0.2858
tmp$state[m] <- "healthy"

tmp %>% 
  filter(V_osc/V_comp <= 5) %>%
  group_by(freq, N) %>%
  # mutate(errors_pop = normalize(errors_pop)) %>%
  # mutate(variances_pop = normalize(variances_pop)) %>%
  ggplot(aes(x=variances_pop, errors_pop, group=freq, color=state)) +
  geom_point(size=1.2, alpha=0.8) +
  xlab("Norm. variance") +
  ylab("Norm. error") +
  scale_color_manual("State", values=c("darkslategray3", "darkslategray")) +
  theme_classic() +
  theme(legend.background = element_rect(colour ="black")) 
```