---
title: "Exp134: Sparse coordination - general experiment analysis."
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(magrittr)
library(readr)
library(gridExtra)
library(readr)
library(scales)
library(dplyr)
library(NNTbiomarker)

normalize <- function(x) {
    return ((x - min(x)) / (max(x) - min(x)))
}
find_point <- function(x, y, point){
  i <- argmin(x, target = point)
  return(c(x[i], y[i]))
}
ms <- 1e3
```


# Load and process

```{r, message=FALSE}
freqs <- c("8")#, "40", "60")
results <- NULL

# Sparse exps
# exp <- "134_1"
# tmp <- NULL
# for(freq in freqs){
#   name <- paste("../../data/exp", exp, ".csv", sep="")
#   df <- read_csv(paste(name, sep=""))
#   df$freq <- rep(freq, nrow(df))
#   tmp <- rbind(tmp, df)
# }
# tmp$exp <- rep(exp, nrow(tmp))
# results <- rbind(results, tmp)
# 
# exp <- "134_2"
# tmp <- NULL
# for(freq in freqs){
#   name <- paste("../../data/exp", exp, ".csv", sep="")
#   df <- read_csv(paste(name, sep=""))
#   df$freq <- rep(freq, nrow(df))
#   tmp <- rbind(tmp, df)
# }
# tmp$exp <- rep(exp, nrow(tmp))
# results <- rbind(results, tmp)
# 
# exp <- "134_3"
# tmp <- NULL
# for(freq in freqs){
#   name <- paste("../../data/exp", exp, ".csv", sep="")
#   df <- read_csv(paste(name, sep=""))
#   df$freq <- rep(freq, nrow(df))
#   tmp <- rbind(tmp, df)
# }
# tmp$exp <- rep(exp, nrow(tmp))
# results <- rbind(results, tmp)
# 
# exp <- "134_4"
# tmp <- NULL
# for(freq in freqs){
#   name <- paste("../../data/exp", exp, ".csv", sep="")
#   df <- read_csv(paste(name, sep=""))
#   df$freq <- rep(freq, nrow(df))
#   tmp <- rbind(tmp, df)
# }
# tmp$exp <- rep(exp, nrow(tmp))
# results <- rbind(results, tmp)

exp <- "134_5"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)

exp <- "134_6"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)

exp <- "134_7"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)

exp <- "134_8"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)

# Org dense code
exp <- "132b"
tmp <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  tmp <- rbind(tmp, df)
}
tmp$exp <- rep(exp, nrow(tmp))
results <- rbind(results, tmp)


# -
# Process
results %>% 
  filter(n_spikes_ref > 0) %>% 
  # Add delta_spikes
  mutate(delta_spikes = n_spikes - n_spikes_ref) %>% 
  # Re-norm V_osc
  mutate(V_osc = V_osc - V_osc_ref) -> results


results %>% 
  group_by(As, freq, exp) %>% 
  summarise(
    N = 0,
    delta_spikes = mean(delta_spikes), 
    V_b = mean(V_b), 
    V_osc = mean(V_osc), 
    V_free = mean(V_free), 
    V_comp = mean(V_comp), 
    V_comp_ref = mean(V_comp_ref), 
    n_spikes_pop = mean(n_spikes), 
    errors = mean(errors), 
    errors_pop = mean(errors_pop), 
    variances_pop = mean(variances_pop),
    # N_oscs = mean(N_oscs),
    variances = mean(variances)) -> avg_results

# -
rm(tmp, df)
```

# Plot
## Variance and error
### As
```{r}
avg_results %>% 
  ggplot(aes(x=As, y=variances_pop*ms, color=as.factor(exp), shape=as.factor(exp))) +
  geom_line(size=1, alpha=0.6) +
  # geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

```{r}
avg_results %>% 
  ggplot(aes(x=As, y=n_spikes_pop, color=as.factor(exp), shape=as.factor(exp))) +
  geom_line(size=1, alpha=0.6) +
  # geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

```{r}
avg_results %>% 
  ggplot(aes(x=As, y=errors_pop*ms, color=as.factor(exp), shape=as.factor(exp))) +
  geom_line(size=1, alpha=0.6) +
  # geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

### Ratio

```{r}
avg_results %>% 
  filter(V_osc/V_comp < 5) %>% 
  ggplot(aes(x=V_osc/V_comp, y=variances_pop*ms, color=as.factor(exp), shape=as.factor(exp))) +
  geom_line(size=1, alpha=0.6) +
  # geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

```{r}
avg_results %>% 
  filter(V_osc/V_comp < 5) %>% 
  ggplot(aes(x=V_osc/V_comp, y=n_spikes_pop, color=as.factor(exp), shape=as.factor(exp))) +
  geom_line(size=1, alpha=0.6) +
  # geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

```{r}
avg_results %>% 
  filter(V_osc/V_comp < 5) %>% 
  ggplot(aes(x=V_osc/V_comp, y=errors_pop*ms, color=as.factor(exp), shape=as.factor(exp))) +
  geom_line(size=1, alpha=0.6) +
  # geom_point(size=2, alpha=0.8) +
  # facet_grid(exp~.) +
  theme_classic()
```

## Trade-off
```{r}
avg_results %>% 
  filter(V_osc/V_comp < 1) %>% 
  ggplot(aes(x=variances_pop*ms, y=errors_pop*ms, color=as.factor(exp), shape=as.factor(exp))) +
  geom_point(size=1, alpha=0.6) +
  # geom_point(size=1, alpha=0.8) +
  # geom_boxplot() +
  # facet_grid(exp~.) +
  theme_classic()
```

```{r}
avg_results %>% 
  filter(V_osc/V_comp < 1) %>% 
  ggplot(aes(x=errors_pop*ms, y=variances_pop*ms, color=as.factor(exp))) +
  # geom_line(size=1, alpha=0.6) +
  geom_point(size=2, alpha=0.8) +
  # geom_boxplot() +
  # facet_grid(exp~.) +
  theme_classic()
```


```{r}
avg_results %>% 
  filter(V_osc/V_comp < 1) %>% 
  group_by(exp) %>% 
  mutate(errors_pop=normalize(errors_pop), variances_pop=normalize(variances_pop)) %>% 
  ggplot(aes(x=errors_pop, y=variances_pop, color=as.factor(exp))) +
  geom_line(size=1, alpha=0.6) +
  # geom_point(size=2, alpha=0.8) +
  # geom_boxplot() +
  # facet_grid(exp~.) +
  theme_classic()
```