---
title: "Sweep A - general experiment analysis."
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(gridExtra)
library(readr)

normalize <- function(x) {
    return ((x - min(x)) / (max(x) - min(x)))
}
```


# Load and process

```{r, message=FALSE}
results <- NULL

# --------------------------
exp <- "77"
freqs <- c(24, 30, 40)

for(freq in freqs){
  name <- paste("../data/exp", exp, "_d-2e-3_f", as.character(freq), ".csv", sep="")
  df <- read_csv(paste(name, sep=","))
  df %>%
    filter(n_spikes > 0) -> df
  
  df$freq <- rep(freq, nrow(df))
  results <- rbind(results, df)
}

# --------------------------
exp <- "79"
freqs <- c(6, 8, 10, 12, 14, 16, 18, 20)

for(freq in freqs){
  name <- paste("../data/exp", exp, "_d-2e-3_f", as.character(freq), ".csv", sep="")
  df <- read_csv(paste(name, sep=","))
  df %>%
    filter(n_spikes > 0) -> df
  
  df$freq <- rep(freq, nrow(df))
  results <- rbind(results, df)
}

exp <- "80"
freqs <- c(22, 24, 26, 28, 32, 34 ,36, 38)
for(freq in freqs){
  name <- paste("../data/exp", exp, "_d-2e-3_f", as.character(freq), ".csv", sep="")
  df <- read_csv(paste(name, sep=","))
  df %>%
    filter(n_spikes > 0) -> df
  
  df$freq <- rep(freq, nrow(df))
  results <- rbind(results, df)
}

# --------------------------
# Process
results %>% 
  # Add delta_spikes
  mutate(delta_spikes = n_spikes - n_spikes_ref) %>% 
  # Re-norm V_osc
  mutate(V_osc = V_osc - V_osc_ref) -> results

results %>% 
  group_by(As, freq) %>% 
  summarise(
    V_b = mean(V_b),
    V_osc = mean(V_osc),
    delta_spikes = mean(delta_spikes),
    V_comp = mean(V_comp), 
    errors = mean(errors), 
    variances = mean(variances)) -> avg_results

rm(df, exp, freq, freqs, name)
```

```{r, fig.width=1.2, fig.height=0.8}
avg_results %>%
  ggplot(aes(x=As*1e9, y=V_osc*1e3, color=freq)) +
  geom_point(size=0.05, alpha=0.2) + 
  labs(x="As (namp)", y="Vo (mvolt)") +
  theme_classic() +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8)) 
```

```{r, fig.width=1.2, fig.height=0.8}
avg_results %>%
  ggplot(aes(x=As*1e9, y=errors*1e3, color=freq)) +
  geom_point(size=0.05, alpha=0.2) + 
  labs(x="As (namp)", y="Error (ms)") +
  theme_classic() +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8)) 
```

```{r, fig.width=1.2, fig.height=0.8}
avg_results %>%
  ggplot(aes(x=As*1e9, y=variances*1e3, color=freq)) +
  geom_point(size=0.05, alpha=0.2) + 
  labs(x="As (namp)", y="Variance (ms)") +
  theme_classic() +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8)) 
```


### V_osc/V_b

```{r, fig.width=1.2, fig.height=0.8}
avg_results %>% 
  ggplot(aes(x=V_osc/V_b, y=delta_spikes, color=freq, group=freq)) +
  geom_jitter(alpha=0.2, size=0.1) + 
  labs(x="V_osc/V_b", y="Spike count") +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme_classic() +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8))
```

```{r, fig.width=1.2, fig.height=0.8}
avg_results %>% 
  ggplot(aes(x=V_osc/V_b, y=errors, color=freq, group=freq)) +
  geom_jitter(alpha=0.2, size=0.1) + 
  labs(x="V_osc/V_b", y="Error (ms)") +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme_classic() +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8))
```

```{r, fig.width=1.2, fig.height=0.8}
avg_results %>% 
  ggplot(aes(x=V_osc/V_b, y=variances, color=freq, group=freq)) +
  geom_jitter(alpha=0.2, size=0.1) + 
  labs(x="V_osc/V_b", y="Variance (ms)") +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme_classic() +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8))
```

### V_osc/V_comp

```{r, fig.width=1.2, fig.height=0.8}
avg_results %>% 
  ggplot(aes(x=V_osc/V_comp, y=errors, color=freq, group=freq)) +
  geom_jitter(alpha=0.2, size=0.1) + 
  labs(x="V_osc/V_comp", y="Error (ms)") +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme_classic() +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8))
```

```{r, fig.width=1.2, fig.height=0.8}
avg_results %>% 
  ggplot(aes(x=V_osc/V_comp, y=variances, color=freq, group=freq)) +
  geom_jitter(alpha=0.2, size=0.1) + 
  labs(x="V_osc/V_comp", y="Variance (ms)") +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme_classic() +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8))
```


```{r, fig.width=2.9, fig.height=2}
avg_results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  filter(errors*1e3 < 30) %>% 
  ggplot(aes(x=V_osc/V_comp, y=errors*1e3)) +
  geom_point(size=0.01, alpha=0.9, color="black") + 
  theme_classic() +
  geom_vline(xintercept = 1, alpha=0.7, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.5, color="purple", linetype="dashed") +
  facet_wrap(~freq) +
  theme(legend.position="bottom") 
```


```{r, fig.width=2.9, fig.height=2}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  filter(errors*1e3 < 30) %>% 
  ggplot(aes(x=V_osc/V_comp, y=errors*1e3)) +
  geom_point(size=0.01, alpha=0.01, color="grey") + 
  theme_classic() +
  geom_vline(xintercept = 1, alpha=0.7, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.5, color="purple", linetype="dashed") +
  facet_wrap(~freq) +
  theme(legend.position="bottom") 
```


### Var

```{r, fig.width=1.3, fig.height=0.8}
avg_results %>% 
  ggplot(aes(x=V_osc*1e3, y=variances, color=freq, group=freq)) +
  geom_jitter(alpha=0.2, size=0.1) + 
  labs(x="V_osc (mvolt)", y="Variance (ms)") +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme_classic() +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8))
```

```{r, fig.width=1.2, fig.height=0.8}
results %>%
  filter(rank == 0) %>% 
  ggplot(aes(x=errors_pop*1e3, y=variances_pop*1e3, color=freq)) +
  geom_point(size=0.05, alpha=0.2) + 
  labs(x="Error (ms)", y="Variance (ms)") +
  theme_classic() +
  scale_color_gradient(low="gold", high="darkgreen") +
  theme(legend.position="right", 
    legend.key.size = unit(.4, "cm"),
    legend.title = element_text(size=8),
    legend.text = element_text(size=8)) 
```
