---
title: "Exp1 - Opt w_max and {A,phi)"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(gridExtra)
library(readr)

normalize <- function(x) {
    return ((x - min(x)) / (max(x) - min(x)))
}
```

# Voltage budget timecourse

```{r}
vms <- read_csv("vm_comp_timecourse.csv")
```

```{r, fig.width=1.5, fig.height=1.3}
vms %>% 
  filter(t > 0.15, t < 0.35) %>%
  ggplot(aes(x=t, ymin=-70e-3, ymax=vm)) +
  geom_ribbon(fill="blue", alpha=0.5) +
  geom_hline(yintercept=-50e-3, color="black", linetype="dotted", size=0.5) +
  geom_hline(yintercept=-70e-3, color="black", linetype="dotted", size=0.5) +
  labs(x="", y="Vm") +
  theme_classic() -> p1

vms %>% 
  filter(t > 0.15, t < 0.35) %>%
  ggplot(aes(x=t, ymin=-70e-3, ymax=osc)) +
  geom_ribbon(fill="red", alpha=0.5) +
  geom_ribbon(aes(x=t, ymin=osc, ymax=comp), fill="purple", alpha=0.5) +
  geom_hline(yintercept=-50e-3, color="black", linetype="dotted", size=0.5) +
  geom_hline(yintercept=-70e-3, color="black", linetype="dotted", size=0.5) +
  geom_rect(aes(xmin=0.23652 - 8e-3, xmax=0.23652 + 2e-3 + 0.03333333 + 8e-3, ymin=-70e-3, ymax=-50e-3),  fill=NA, color="black", alpha=0.01, size=.2) +
  # geom_hline(yintercept=-70e-3, color="black", size=1.5) +
  # geom_rect(aes(xmin=0.23652 - 2e-3, xmax=0.23652, ymin=-70e-3, ymax=-50e-3), color="grey", alpha=0.5) +
  # geom_rect(aes(xmin=0.23652 + 2e-3, xmax=0.23652 + 2e-3 + 0.03333333, ymin=-70e-3, ymax=-50e-3), fill=NA, color="grey", alpha=0.1) +
  labs(x="Times (s)", y="") +
  theme_classic() -> p2

vms %>% 
  filter(t > 0.23652 - 8e-3, t < 0.23652 + 2e-3 + 0.03333333 + 8e-3) %>%
  ggplot(aes(x=t, ymin=-70e-3, ymax=osc)) +
  geom_ribbon(fill="red", alpha=0.5) +
  geom_ribbon(aes(x=t, ymin=osc, ymax=comp), fill="purple", alpha=0.5) +
  # geom_hline(yintercept=-50e-3, color="black", linetype="dotted", size=0.5) +
  # geom_hline(yintercept=-70e-3, color="black", linetype="dotted", size=0.5) +
  geom_rect(aes(xmin=0.23652 - 2e-3, xmax=0.23652, ymin=-70e-3, ymax=-50e-3), fill="grey", alpha=0.01) +
  geom_rect(aes(xmin=0.23652 + 2e-3, xmax=0.23652 + 2e-3 + 0.03333333, ymin=-70e-3, ymax=-50e-3),  fill="grey", alpha=0.01) +
  geom_rect(aes(xmin=0.23652 - 8e-3, xmax=0.23652 + 2e-3 + 0.03333333 + 8e-3, ymin=-70e-3, ymax=-50e-3),  fill=NA, color="black", alpha=0.01, size=.2) +
  labs(x="", y="") +
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      # axis.title.x=element_blank(),
      # axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank()) -> p3

plot_grid <- rbind(c(1 , 1, NA), c(2, 2, 3))
grid.arrange(p1, p2, p3, layout_matrix=plot_grid)
```
           

# Bounds

```{r, message=FALSE, fig.width=3, fig.height=1.7}
# --------------------------------------------------------------
# V-fre dist
name <- "../data/exp28_d-0.2e-3_f20.csv"
results <- read_csv(paste(name, sep=""))

results %>% 
  filter(V_free > 0.002) %>% 
  ggplot(aes(x=V_free*1e3)) +
  geom_histogram(aes(y=0.5*..density..), bins=50, size=0.2) +
  geom_density(alpha=0.3, fill="black") +
  geom_vline(aes(xintercept=min(1e3*V_free - 0.05)), color="darkolivegreen3", alpha=0.6) +
  geom_vline(aes(xintercept=max(1e3*V_free + 0.01)), color="goldenrod2", alpha=0.5) +
  labs(x="V_free (mvolt)", y="Density (AU)") +
  xlim(1, 6) +
  theme_classic() -> p1

results %>%
  filter(V_free > 0.002) %>%
  ggplot(aes(x=variances, y=errors, color=V_free)) +
  geom_point(alpha=0.5) +
  scale_color_gradient(low="darkolivegreen3", high="goldenrod2") +
  theme_classic() -> p2

# --------------------------------------------------------------
# rank 1/50
# Load min, max V_free and neighbors
name <- "../data/exp29_d-0.2e-3_f20_r1.csv"
rank1 <- read_csv(paste(name, sep=""))
rank1$rank <- rep(1, nrow(rank1))

# name <- "../data/exp5_d-2e-3_f8_r2.csv"
# rank2 <- read_csv(paste(name, sep=""))
# rank2$rank <- rep(2, nrow(rank2))
# 
# name <- "../data/exp5_d-2e-3_f8_r3.csv"
# rank3 <- read_csv(paste(name, sep=""))
# rank3$rank <- rep(3, nrow(rank3))

name <- "../data/exp29_d-0.2e-3_f20_r5.csv"
rank50 <- read_csv(paste(name, sep=""))
rank50$rank <- rep(50, nrow(rank50))

# name <- "../data/exp5_d-2e-3_f8_r49.csv"
# rank49 <- read_csv(paste(name, sep=""))
# rank49$rank <- rep(49, nrow(rank49))
# 
# name <- "../data/exp5_d-2e-3_f8_r48.csv"
# rank48 <- read_csv(paste(name, sep=""))
# rank48$rank <- rep(48, nrow(rank48))

# Group 'em
# ranked <- rbind(rank1, rank2, rank3, rank50, rank49, rank48)
ranked <- rbind(rank1, rank50)
# ranked$rank <- as.factor(ranked$rank)
# -----------------------------------------------------
# TODO: manual color assignment, setting alphas to rank?
ranked %>%
  ggplot(aes(x=N, y=sort(errors), color=rank, group=rank)) +
  geom_line(alpha=0.4) +
  scale_color_continuous(low="darkolivegreen3", high="goldenrod2") +
  theme_classic() -> p3

ranked %>%
  ggplot(aes(x=N, y=sort(variances), color=rank, group=rank)) +
  geom_line(alpha=0.4) +
  scale_color_gradient(low="darkolivegreen3", high="goldenrod2") +
  theme_classic() -> p4

plot_grid <- rbind(c(1 , 1, 1, 3, 3, 3), c(1 , 1, 1, 3, 3, 3), c(1, 1, 1, 4, 4, 4), c(NA, NA, NA, 4, 4, 4))
grid.arrange(p1, p3, p4, layout_matrix=plot_grid)
```

# Pareto opt
```{r, message=FALSE, fig.width=2.2, fig.height=1.9}
name <- "../data/exp36_d-0.2e-3_f20.csv"
results <- read_csv(paste(name, sep=""))
results %>% 
  filter(n_spikes > 0, errors > 1e-5, V_osc < 7e-3) -> results

results %>% 
  # filter(errors < 0.6, variances > 0) %>%
  ggplot(aes(y=V_comp*1e3, x=V_osc*1e3, color=As*1e9)) +
  scale_color_gradient(low="mediumpurple", high="red3", name="A\n(namp)") +
  xlab("Vo (mvolt)") + ylab("Vc (mvolt)") +
  geom_point(alpha=0.4) + 
  xlim(4.5, 7) +
  theme_classic() + 
  theme(legend.position="bottom", legend.key.size =  unit(0.25, "in")) -> p1


# results %>% 
#   ggplot(aes(x=1e3*V_free, y=normalize(variances))) +
#   geom_smooth(method = "glm",  method.args = list(family = "binomial"), color="red3", alpha=0.5, se=FALSE, linetype="dashed") + 
#   geom_point(color="red3", alpha=0.2) +
#   geom_smooth(aes(x=1e3*V_free, y=normalize(errors)), 
#               method = "glm",  method.args = list(family = "binomial"), color="mediumpurple", se=FALSE,linetype="dashed") + 
#   geom_point(aes(x=1e3*V_free, y=normalize(errors)), color="mediumpurple", alpha=0.2) +
#   geom_vline(aes(xintercept = mean(1e3*V_free)), color="black") +
#   xlab("Vf (mvolt)") +
#   ylab("Normalized") +
#   theme_classic() -> p2


results %>% 
  ggplot(aes(x=1e3*V_osc, y=errors*1e3)) +
  geom_point(alpha=0.4, size=.5, color="mediumpurple") +
  geom_smooth(color="mediumpurple", alpha=0.2, size=0.8, se=FALSE, linetype="dashed") +
  # geom_smooth(method = 'nls', formula = y ~ x, se = FALSE) + #, start=list(b=1)) #, start = list(a=1,b=.1)) +
  xlab("Vo (mvolt)") +
  ylab("Error (ms)") +
  xlim(4.5, 7) +
  # ylim(0, 1e3*5e-3) +
  theme_classic() -> p3


results %>% 
  ggplot(aes(x=1e3*V_osc, y=variances*1e3)) +
  geom_point(alpha=0.3, size=.5, color="red3") +
  geom_smooth(color="red3", alpha=0.5, size=0.8, se=FALSE, linetype="dashed", formula = y ~ x, method=lm) +
  xlab("Vo (mvolt)") +
  ylab("Variance (ms)") +
  xlim(4.5, 7) +
  # ylim(1e3*0.0096, 1e3*0.0102) +
  theme_classic() -> p4




# plot_grid <- rbind(c(NA ,NA, 3, 3), c(NA, NA, 3, 3), c(NA, NA, 4, 4), c(1 ,1, 4, 4), c(1, 1, 2, 2), c(1, 1, 2, 2))
# grid.arrange(p1, p2, p3, p4, layout_matrix=plot_grid)

plot_grid <- rbind(c(NA ,NA, 2, 2), 
                   c(NA, NA, 2, 2), 
                   c(NA, NA, 2, 2), 
                   c(1, 1, 2, 2), 
                   c(1, 1, 3, 3), 
                   c(1, 1, 3, 3), 
                   c(1, 1, 3, 3), 
                   c(1 ,1, 3, 3),
                   c(NA ,NA, NA, NA))
grid.arrange(p1, p3, p4, layout_matrix=plot_grid)
```


# Optimal PLC 

```{r, message=FALSE}
plc_spikes <- read_csv("plc_spikes.csv")
plc_traces <- read_csv("plc_traces.csv")
```

```{r, fig.width=0.6, fig.height=1}
plc_spikes %>% 
  ggplot(aes(x=ts_opt, y=n)) + 
  geom_point(color="black", size=0.8) +
  geom_point(data=filter(plc_spikes, ts != ts_opt), aes(x=ts, y=n), color="red", size=1.5, shape=4, alpha=0.6) +
  xlim(0.2, 0.24) +
  theme_classic() +
  # labs(x="Time (s)", y="N") +
  theme(axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major.y=element_blank(),
      panel.grid.minor.y =element_blank(),
      plot.background=element_blank()) -> p1
```

```{r, fig.width=1.2, fig.height=1}
plc_traces %>% 
  ggplot(aes(x=variances, y=errors)) +
  geom_line() +
  theme_classic() +
  ylab("Errors (s)") +
  xlab("Variance (s)") -> p2
```

```{r, fig.width=2.25, fig.height=1}
plot_grid <- rbind(c(1, 1, NA, 2, 2, 2),c(1, 1, NA, 2, 2, 2),c(NA, NA, NA, 2, 2, 2))
grid.arrange(p1, p2, layout_matrix=plot_grid)
```