---
title: "Optimal coordination - general experiment analysis."
output: html_notebook
---

```{r, message=FALSE}
library(ggplot2)
library(magrittr)
library(readr)
library(gridExtra)
library(readr)
library(scales)
library(dplyr)
library(NNTbiomarker)

normalize <- function(x) {
    return ((x - min(x)) / (max(x) - min(x)))
}
find_point <- function(x, y, point){
  i <- argmin(x, target = point)
  return(c(x[i], y[i]))
}

```


# Load and process

```{r, message=FALSE}
# Sparse
exp <- "124"
freqs <- c("4", "8", "12", "20", "24", "30")#, "40", "60")


results <- NULL
for(freq in freqs){
  name <- paste("../../data/exp", exp, "_d-2e-3_f", freq, ".csv", sep="")
  df <- read_csv(paste(name, sep=""))
  df$freq <- rep(freq, nrow(df))
  results <- rbind(results, df)
}
results$freq <- factor(results$freq, levels=freqs)


results %>% 
  filter(n_spikes_ref > 0) %>% 
  # Add delta_spikes
  mutate(delta_spikes = n_spikes - n_spikes_ref) %>% 
  # Re-norm V_osc
  mutate(V_osc = V_osc - V_osc_ref) -> results

rm(tmp, df)

# --------------------------
# Dense
ref <- NULL

exp <- "96"
freqs <- c(20, 30)

for(freq in freqs){
  name <- paste("../../data/exp", exp, "_d-2e-3_f", as.character(freq), ".csv", sep="")
  df <- read_csv(paste(name, sep=","))
  df %>%
    filter(n_spikes > 0) -> df
  
  df$freq <- rep(freq, nrow(df))
  ref <- rbind(ref, df)
}

# --------------------------
# SLOW
exp <- "94"
freqs <- c(6, 8, 10, 12, 14, 16, 18)

for(freq in freqs){
  name <- paste("../../data/exp", exp, "_d-2e-3_f", as.character(freq), ".csv", sep="")
  df <- read_csv(paste(name, sep=","))
  df %>%
    filter(n_spikes > 0) -> df
  
  df$freq <- rep(freq, nrow(df))
  ref <- rbind(ref, df)
}

# --------------------------
# FAST
exp <- "95"
freqs <- c(22, 24, 26, 28)#, 32, 34 ,36, 38)
for(freq in freqs){
  name <- paste("../../data/exp", exp, "_d-2e-3_f", as.character(freq), ".csv", sep="")
  df <- read_csv(paste(name, sep=","))
  df %>%
    filter(n_spikes > 0) -> df
  
  df$freq <- rep(freq, nrow(df))
  ref <- rbind(ref, df)
}

# Process
ref %>% 
  filter(n_spikes_ref > 0) %>% 
  # Add delta_spikes
  mutate(delta_spikes = n_spikes - n_spikes_ref) %>% 
  # Re-norm V_osc
  mutate(V_osc = V_osc - V_osc_ref) -> ref

rm(tmp, df)
```
```{r}
results %>% 
  ggplot(aes(x=As, y=variances_pop, color=freq)) +
  geom_point(size=0.1) +
  theme_classic()
```

```{r}
results %>% 
  ggplot(aes(x=As, y=errors_pop, color=freq)) +
  geom_point(size=0.1) +
  theme_classic()
```

```{r}
tmp <- results
tmp$state <- rep("pathological", nrow(tmp))
m <- tmp$V_osc/tmp$V_comp < 0.2858
tmp$state[m] <- "healthy"

tmp %>% 
  filter(V_osc/V_comp <= 5) %>%
  group_by(freq, N) %>%
  # mutate(errors_pop = normalize(errors_pop)) %>%
  # mutate(variances_pop = normalize(variances_pop)) %>%
  ggplot(aes(x=variances_pop, errors_pop, group=freq, color=state)) +
  geom_point(size=1.2, alpha=0.8) +
  xlab("Norm. variance") +
  ylab("Norm. error") +
  scale_color_manual("State", values=c("darkslategray3", "darkslategray")) +
  theme_classic() +
  theme(legend.background = element_rect(colour ="black")) 
```