---
title: "Sweep A - general experiment analysis."
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(gridExtra)
library(readr)
library(scales)

normalize <- function(x) {
    return ((x - min(x)) / (max(x) - min(x)))
}
```


# Load and process

```{r, message=FALSE}
name <- "../data/exp96_d-2e-3_f20.csv"  

results <- read_csv(paste(name, sep=""))

rm(name)

# Add delta_spikes
results %>% 
  filter(n_spikes_ref > 0) %>%
  mutate(delta_spikes = n_spikes - n_spikes_ref) %>% 
  mutate(V_osc = V_osc - V_osc_ref) -> results
```


# Overall distributions

```{r, fig.width=1.9, fig.height=2.3}
results %>% 
  ggplot(aes(x=variances*1e3)) +
  geom_histogram(bins=20) + 
  xlab("Variance (ms)") +
  theme_classic() -> p1

results %>% 
  ggplot(aes(x=errors*1e3)) +
  geom_histogram(bins=20) + 
  xlab("Error (ms)") +
  theme_classic() -> p2

results %>% 
  ggplot(aes(x=V_osc*1e3)) +
  geom_histogram(bins=20) +
  xlab("V_osc (mvolt)") +
  theme_classic() -> p3

results %>% 
  ggplot(aes(x=V_comp*1e3)) +
  geom_histogram(bins=20) +
  xlab("V_comp (mvolt)") +
  theme_classic() -> p4

results %>% 
  ggplot(aes(x=V_osc/V_b)) +
  geom_histogram(bins=20) +
  xlab("V_osc/Vb (AU)") +
  xlim(0, 1) +
  theme_classic() -> p5

results %>% 
  ggplot(aes(x=V_comp/V_b)) +
  geom_histogram(bins=20) +
  xlab("V_comp/Vb (AU)") +
  xlim(0, 1) +
  theme_classic() -> p6

results %>% 
  ggplot(aes(x=V_osc/V_comp)) +
  geom_histogram(bins=20) +
  xlab("V_osc/V_comp (AU)") +
  theme_classic() -> p7

grid.arrange(p1, p2, p3, p4, p5, p6, p7, nrow=4)
rm(p1, p2, p3, p4, p5, p6, p7)
```

# Pop level
## As

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  # filter(rank == 0) %>% 
  ggplot(aes(x=As*1e9, y=variances_pop)) +
  geom_point(size=0.1) + 
  theme_classic() +
  theme(legend.position="bottom") 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  # filter(rank == 0) %>% 
  ggplot(aes(x=As*1e9, y=errors_pop)) +
  geom_point(size=0.1) + 
  theme_classic() 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  # filter(rank == 0) %>%
  ggplot(aes(x=As*1e9, y=n_spikes_pop)) +
  geom_point(size=0.1) + 
  theme_classic() 
```


## Metrics

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  # filter(rank == 0) %>%
  ggplot(aes(x=variances_pop*1e3, y=errors_pop*1e3)) +
  geom_point(size=0.1) + 
  theme_classic() 
```

# N level
## del. spikes

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(y=1e9*As, x=delta_spikes)) +
  geom_jitter(alpha=0.01, size=0.1) + 
  ylab("As (namp)") +
  theme_classic() +
  coord_flip()
```

## Error

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(x=1e9*As, y=errors)) +
  geom_point(size=0.1, alpha=0.1) + 
  theme_classic() 
```


```{r, fig.width=3.2, fig.height=1.7}
M = median(results$errors)
results %>% 
  ggplot(aes(x=1e9*As, y=errors)) +
  geom_point(size=0.1, alpha=0.1) + 
  facet_grid(delta_spikes~n_spikes_ref) +
  xlab("As (namp)") +
  theme_classic() 
rm(M)
```

```{r, fig.width=4.0, fig.height=4}
results %>% 
  filter(rank < 20) %>% 
  ggplot(aes(x=1e9*As, y=errors, color=factor(delta_spikes))) +
  geom_point(size=1, alpha=1) +
  facet_wrap(~rank) +
  theme_classic() + theme(legend.position="bottom") +
  scale_colour_brewer(palette = "Accent") +
  xlab("As") 
```


## Var

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  group_by(N) %>%
  mutate(V_free_initial = round(max(V_free), 3)) %>%
  filter(V_free_initial > 0) %>%
  ggplot(aes(x=1e9*As, y=variances, group=N, color=factor(delta_spikes))) +
  geom_line(size=0.4, alpha=0.6) + 
  scale_colour_brewer(palette = "Accent") +
  theme_classic() + theme(legend.position="bottom") 
```


## Vo

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(x=As*1e9, y=1e3*V_osc)) +
  geom_point(size=0.1, alpha=0.01) + 
  ylab("V_osc (mvolt)") +
  xlim(0, .15) +
  theme_classic() 
```


```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(x=V_osc*1e3, y=errors)) +
  geom_point(size=0.1, alpha=0.01) + 
  xlab("V_osc (mvolt)") +
  theme_classic() 
```

```{r, fig.width=1.2, fig.height=1.5}
results %>% 
  group_by(N) %>%
  mutate(V_free_initial = round(max(V_free), 3)) %>%
  filter(V_free_initial > 0) %>%
  ggplot(aes(x=V_osc*1e3, y=variances, group=N)) +
  geom_line(size=0.4, alpha=0.9) + 
  scale_colour_brewer(
    palette = "Accent", guide=guide_legend(title="Spike count", nrow=3)) +
  xlab("V_osc (mvolt)") +
  theme_classic() + theme(legend.position="bottom") 
```

```{r, fig.width=1.2, fig.height=1.5}
results %>% 
  group_by(N) %>%
  mutate(V_free_initial = round(max(V_free), 3)) %>%
  filter(V_free_initial > 0) %>%
  ggplot(aes(x=V_osc*1e3, y=variances, group=N, color=factor(delta_spikes))) +
  geom_line(size=0.4, alpha=0.9) + 
  scale_colour_brewer(
    palette = "Accent", guide=guide_legend(title="Spike count", nrow=3)) +
  xlab("V_osc (mvolt)") +
  theme_classic() + theme(legend.position="bottom") 
```
```{r,fig.width=1.2, fig.height=0.8}
M = min(fig1$variances_pop)

results %>% 
  ggplot(aes(x=variances, fill=factor(delta_spikes))) +
  geom_density(alpha=0.6, size=0, color="black") +
  scale_fill_brewer(palette = "Accent", name="Spike count") +
  geom_vline(xintercept = M, color="black") +
  theme_classic() + theme(legend.position="none") 
```

### Deciles

```{r, fig.width=2.25, fig.height=1.15}
# M = min(avg_results$variances)
# 
# results %>% 
#   mutate(quantile = ntile(V_osc, 10)) %>%
#   filter(quantile %in% c(1, 10)) %>% 
#   ggplot(aes(x=variances, fill=factor(quantile), group=quantile)) +
#   # geom_histogram(bins=20, alpha=0.8, ) + 
#   geom_density(alpha=0.6, size=0.2, color="black") +
#   geom_vline(xintercept = M, color="black") +
#   # facet_wrap(~quantile) +
#   xlab("Variance (ms)") +
#   scale_fill_manual(
#     values=c("#FFDED3", "#FD0D11"), 
#     name=expression("Quantiles V"[o]), 
#     labels=c("0 - 10%", "90 - 100%")) +
#   theme_classic()
# 
# rm(M)
```

## Metrics

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  # filter(variances > 0.005) %>% 
  ggplot(aes(x=variances*1e3, y=errors*1e3)) +
  geom_point(size=0.01, alpha=0.1) + 
  xlab("variances (ms)") + ylab("error (ms)") +
  theme_classic() 
```

```{r, fig.width=2.3, fig.height=2.5}
results %>% 
  ggplot(aes(x=variances*1e3, y=errors*1e3, color=1e9*As)) +
  geom_point(size=0.01, alpha=0.6) + 
  facet_grid(delta_spikes ~ n_spikes_ref) +
  xlab("variances (ms)") + ylab("error (ms)") +
  scale_color_gradient(low="darkgrey", high="red") +
  theme_classic() + theme(legend.position="bottom") 
```

```{r, fig.width=4.0, fig.height=4}
results %>% 
  filter(rank < 20) %>% 
  ggplot(aes(x=variances*1e3, y=errors*1e3, color=factor(delta_spikes))) +
  geom_point(size=1, alpha=.8) + 
  facet_wrap(~rank) +
  xlab("variances (ms)") + ylab("error (ms)") +
  theme_classic() + theme(legend.position="bottom") +
  scale_colour_brewer(palette = "Accent") 
```

## Vo by Vc

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(x=V_osc*1e3, y=V_comp*1e3)) +
  geom_point(size=0.1, alpha=0.9) + 
  xlab("V_osc (mvolt)") + ylab("V_comp (mvolt)") +
  theme_classic() 
```


## Vo/Vc
#### Errors

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  ggplot(aes(x=V_osc/V_comp, y=errors)) +
  geom_point(size=0.1, alpha=0.01) + 
  geom_vline(xintercept = 1, alpha=0.8, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.6, color="purple", linetype="dashed") +
  theme_classic() +
  xlab("V_osc/V_comp") 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  group_by(N) %>% 
  mutate(norm_errors = errors/max(errors)) %>% 
  ggplot(aes(x=V_osc/V_comp, y=norm_errors)) +
  geom_point(size=0.1, alpha=0.1) + 
  geom_vline(xintercept = 1, alpha=0.8, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.6, color="purple", linetype="dashed") +
  theme_classic() +
  xlab("V_osc/V_comp") 
```


```{r, fig.width=2.5, fig.height=1.7}
results %>% 
  filter(V_osc/V_comp <= 2) %>% 
  # filter(errors < 0.1) %>% 
  ggplot(aes(x=V_osc/V_comp, y=errors)) +
  geom_point(size=0.1, alpha=0.1) + 
  facet_grid(delta_spikes ~ n_spikes_ref) +
  geom_vline(xintercept = 1, alpha=0.8, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.6, color="purple", linetype="dashed") +
  theme_classic() +
  xlab("V_osc/V_comp") 
```

```{r, fig.width=2.5, fig.height=1.7}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  group_by(N) %>% 
  mutate(norm_errors = errors/max(errors)) %>% 
  ggplot(aes(x=V_osc/V_comp, y=norm_errors)) +
  geom_point(size=0.01, alpha=0.05) +
  facet_grid(delta_spikes ~ n_spikes_ref) +
  geom_vline(xintercept = 1, alpha=0.8, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.6, color="purple", linetype="dashed") +
  theme_classic()
```


```{r, fig.width=4.0, fig.height=4}
results %>% 
  filter(rank < 10) %>% 
  filter(V_osc/V_comp <= 3) %>% 
  group_by(N) %>% 
  mutate(norm_errors = errors/max(errors)) %>% 
  ggplot(aes(x=V_osc/V_comp, y=norm_errors, color=factor(delta_spikes))) +
  geom_point(size=1, alpha=0.9) + 
  geom_vline(xintercept = 1, alpha=0.8, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.6, color="purple", linetype="dashed") +
  facet_wrap(~rank) +
  theme_classic() + theme(legend.position="bottom") +
  scale_colour_brewer(palette = "Accent") +
  xlab("V_osc/V_comp") 
```

#### Variances

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  ggplot(aes(x=V_osc/V_comp, y=variances)) +
  geom_point(size=0.1, alpha=0.01) + 
  theme_classic() +
  geom_vline(xintercept = 1, alpha=0.8, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.6, color="purple", linetype="dashed") +
  xlab("V_osc/V_comp_ref") 
```


```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  group_by(N) %>% 
  mutate(norm_variances = variances/max(variances)) %>% 
  ggplot(aes(x=V_osc/V_comp, y=norm_variances)) +
  geom_point(size=0.1, alpha=0.1) + 
  theme_classic() +
  geom_vline(xintercept = 1, alpha=0.8, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.6, color="purple", linetype="dashed") +
  xlab("V_osc/V_comp") 
```



```{r, fig.width=4.5, fig.height=4.5}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  filter(rank < 20) %>% 
  ggplot(aes(x=V_osc/V_comp, y=variances, color=factor(delta_spikes))) +
  geom_point(size=1, alpha=1) + 
  geom_vline(xintercept = 1, alpha=0.8) +
  geom_vline(xintercept = 0.5, alpha=0.4) +
  facet_wrap(~rank) +
  theme_classic() + theme(legend.position="bottom") +
  scale_colour_brewer(palette = "Accent") +
  xlab("V_osc/V_comp") 
```

## Number spikes

### V_osc/V_comp

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  filter(V_osc/V_comp < 3) %>% 
  ggplot(aes(y=V_osc/V_comp, x=delta_spikes)) +
  geom_jitter(size=0.1, alpha=0.01) + 
  geom_hline(yintercept = 1, alpha=0.8, color="purple", linetype="dashed") +
  geom_hline(yintercept = 0.5, alpha=0.6, color="purple", linetype="dashed") +
  theme_classic() +
  ylab("V_osc/V_comp") 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  # filter(V_osc/V_comp < 3) %>% 
  ggplot(aes(y=V_free, x=delta_spikes)) +
  geom_jitter(size=0.1, alpha=0.01) + 
  theme_classic() +
  ylab("V_comp") 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(y=V_osc/V_comp_ref, x=delta_spikes, color=1e3*errors)) +
  geom_jitter(size=0.1, alpha=0.1) + 
  scale_color_gradient(name="Error (ms)", low="grey", high = "purple") +
  theme_classic() +
  ylab("V_osc/V_comp") 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(y=V_osc/V_comp_ref, x=delta_spikes, color=1e3*variances)) +
  geom_jitter(size=0.01, alpha=0.1) + 
  geom_hline(yintercept = 1, alpha=0.8) +
  geom_hline(yintercept = 0.5, alpha=0.4) +
  scale_color_gradient(name="Var (ms)", low="grey", high = muted("blue")) +
  theme_classic() +
  ylab("V_osc/V_comp") 
```


### Var

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(x=delta_spikes, y=variances)) +
  geom_jitter(size=0.1, alpha=0.01) + 
  theme_classic() 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  group_by(As) %>% 
  mutate(delta_spikes = mean(delta_spikes, error=mean(variances))) %>% 
  ggplot(aes(x=delta_spikes, y=variances)) +
  geom_point(size=0.1, alpha=0.01) + 
  theme_classic() 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(x=delta_spikes, y=variances, group=delta_spikes)) +
  geom_boxplot() + 
  theme_classic() 
```

### Error

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(x=delta_spikes, y=errors)) +
  geom_jitter(size=0.1, alpha=0.01) + 
  theme_classic() 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  group_by(As) %>% 
  mutate(delta_spikes = mean(delta_spikes, error=mean(errors))) %>% 
  ggplot(aes(x=delta_spikes, y=errors)) +
  geom_point(size=0.1, alpha=0.01) + 
  theme_classic() 
```

```{r, fig.width=1.25, fig.height=1.15}
results %>% 
  ggplot(aes(x=delta_spikes, y=errors, group=delta_spikes)) +
  geom_boxplot() + 
  theme_classic() 
```
