---
title: "Sweep Z - general experiment analysis."
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(gridExtra)
library(readr)

normalize <- function(x) {
    return ((x - min(x)) / (max(x) - min(x)))
}
data_summary <- function(x) {
   m <- mean(x)
   ymin <- m-mad(x)
   ymax <- m+mad(x)
   return(c(y=m,ymin=ymin,ymax=ymax))
}
mean_summary <- function(x) {
   m <- mean(x)
   return(c(y=m))
}
```


# Load and process

```{r, message=FALSE}
# Osc
freq <- "20"

# Zs scan
exp <- "98"
Zs <- c("0.1", "0.2", "0.3")

results <- NULL
for(Z in Zs){
  name <- paste("../data/exp", exp, "_Z", Z, ".csv", sep="")
  df <- read_csv(paste(name, sep=","))
  
  df$Zs <- rep(as.numeric(Z), nrow(df))
  results <- rbind(results, df)
}

# Ref (Z=0)
exp <- "96"
name <- paste("../data/exp", exp, "_d-2e-3_f", freq, ".csv", sep="")
df <- read_csv(paste(name, sep=","))
df$Zs <- rep(0, nrow(df))
results <- rbind(df, results)

# Process
results %>% 
  filter(n_spikes_ref > 0) %>% 
  mutate(delta_spikes = n_spikes - n_spikes_ref) %>% 
  mutate(V_osc = V_osc - V_osc_ref) %>% 
  mutate(silent = n_spikes_ref == 0) -> results

rm(df, exp, freq, Zs, Z, name)
```

# As

```{r, fig.width=1.5, fig.height=1.5}
results %>% 
  filter(rank == 0) %>% 
  ggplot(aes(x=As, y=n_spikes_pop, color=factor(Zs))) +
  geom_line() + 
  theme_classic() +
  scale_colour_brewer(palette="Greens", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

```{r, fig.width=1.5, fig.height=1.5}
results %>% 
  filter(rank == 0) %>% 
  ggplot(aes(x=As, y=variances_pop, color=factor(Zs))) +
  geom_line() + 
  theme_classic() +
  scale_colour_brewer(palette="Greens", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

```{r, fig.width=1.5, fig.height=1.5}
results %>% 
  filter(rank == 0) %>% 
  ggplot(aes(x=As, y=errors_pop, color=factor(Zs))) +
  geom_line() + 
  theme_classic() +
  scale_colour_brewer(palette="Greens", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

# V_osc/V_b

```{r, fig.width=1.5, fig.height=1.5}
results %>% 
  filter(rank == 0) %>% 
  ggplot(aes(x=V_osc/V_b, y=n_spikes_pop, color=factor(Zs))) +
  geom_line() + 
  theme_classic() +
  scale_colour_brewer(palette="Greens", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

### Errors

```{r, fig.width=1.5, fig.height=1.5}
results %>% 
  filter(rank == 0) %>% 
  ggplot(aes(x=V_osc/V_b, y=errors_pop, color=factor(Zs))) +
  geom_line() + 
  theme_classic() +
  scale_colour_brewer(palette="Greens", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```



```{r, fig.width=1.9, fig.height=1}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  filter(errors < 0.1) %>% 
  ggplot(aes(x=V_osc/V_comp, y=errors*1e3)) +
  geom_point(size=0.01, alpha=0.01) + 
  theme_classic() +
  facet_grid(.~Zs) +
  geom_vline(xintercept = 1, alpha=0.7, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.5, color="purple", linetype="dashed") +
  # scale_colour_brewer(palette="Greys", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

```{r, fig.width=1.9, fig.height=1}
results %>% 
  filter(errors < 0.1) %>%
  filter(V_osc/V_comp <= 3) %>% 
  group_by(N, Zs) %>% 
  mutate(norm_errors = errors/max(errors)) %>% 
  ggplot(aes(x=V_osc/V_comp, y=norm_errors)) +
  geom_point(size=0.01, alpha=0.01) + 
  theme_classic() +
  facet_grid(.~Zs) +
  geom_vline(xintercept = 1, alpha=0.7, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.5, color="purple", linetype="dashed") +
  # scale_colour_brewer(palette="Greys", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

### Variances

```{r, fig.width=1.5, fig.height=1.5}
results %>% 
  filter(rank == 0) %>% 
  ggplot(aes(x=V_osc/V_b, y=variances_pop, color=factor(Zs))) +
  geom_line() + 
  theme_classic() +
  scale_colour_brewer(palette="Greens", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

```{r, fig.width=1.5, fig.height=1.5}
results %>% 
  filter(rank == 0, V_osc/V_comp <= 3) %>% 
  ggplot(aes(x=V_osc/V_comp, y=variances_pop, color=factor(Zs))) +
  geom_line() + 
  theme_classic() +
  scale_colour_brewer(palette="Greens", guide=guide_legend(nrow=3)) +
  geom_vline(xintercept = 1, alpha=0.7, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.5, color="purple", linetype="dashed") +
  theme(legend.position="bottom") 
```


```{r, fig.width=1.9, fig.height=1}
results %>% 
  # filter(V_osc/V_comp <= 3) %>% 
  ggplot(aes(x=V_osc/V_b, y=variances*1e3)) +
  geom_point(size=0.01, alpha=0.01) + 
  theme_classic() +
  facet_grid(.~Zs) +
  # scale_colour_brewer(palette="Greys", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom")
```

```{r, fig.width=1.9, fig.height=1}
results %>% 
  filter(V_osc/V_comp <= 3) %>% 
  ggplot(aes(x=V_osc/V_comp, y=variances*1e3)) +
  geom_point(size=0.01, alpha=0.01) + 
  theme_classic() +
  facet_grid(.~Zs) +
  geom_vline(xintercept = 1, alpha=0.7, color="purple", linetype="dashed") +
  geom_vline(xintercept = 0.5, alpha=0.5, color="purple", linetype="dashed") +
  # scale_colour_brewer(palette="Greys", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

## Metrics

```{r, fig.width=1.5, fig.height=1.5}
results %>% 
  filter(rank == 0) %>% 
  ggplot(aes(x=errors_pop, y=variances_pop, color=factor(Zs))) +
  geom_line() + 
  theme_classic() +
  scale_colour_brewer(palette="Greens", guide=guide_legend(nrow=3)) +
  theme(legend.position="bottom") 
```

## n_spikes v rest

```{r, fig.width=2.25, fig.height=1}
results %>% 
  ggplot(aes(x=delta_spikes, y=errors)) +
  facet_grid(.~Zs) +
  lims(y=c(0, 0.03)) +
  geom_jitter(size=0.1, alpha=0.01) +
  stat_summary(fun.data=data_summary, color="darkgrey", size=0.6, geom="linerange") +
  stat_summary(fun.data=mean_summary, color="darkgrey", size=0.4, geom="point") +
  theme_classic() 
```

```{r, fig.width=2.25, fig.height=1}
results %>% 
  ggplot(aes(x=delta_spikes, y=variances)) +
  facet_grid(.~Zs) +
  # lims(y=c(0, 0.03)) +
  geom_jitter(size=0.1, alpha=0.01) +
  stat_summary(fun.data=data_summary, color="darkgrey", size=0.6, geom="linerange") +
  stat_summary(fun.data=mean_summary, color="darkgrey", size=0.4, geom="point") +
  theme_classic() 
```

